### ISSUE TITLE
bug: image is not accepted when copying unit

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#278] opened 2020-01-01 18:23 UTC
**Describe the bug**
When copying an ad unit, platform says "image size must be exact .." even though it already is. I have to re-upload the image

**To Reproduce**
1. Create a new ad unit
2. Copy it
3. When on the "media" step, you won't be able to advance since the platform will say "image size must be exact.."

**Comment by rori4** [comment] 2020-01-07 10:53
@Ivshti Where have you tested this? I can't reproduce this in development branch.

**Comment by Ivshti** [comment] 2020-01-07 11:27
platform.adex.network

**Comment by Ivshti** [comment] 2020-01-31 10:03
still happens

**Comment by Ivshti** [comment] 2020-01-31 10:04
![Screenshot_2020-01-31 AdEx Platform](https://user-images.githubusercontent.com/1247629/73530784-ce103680-4421-11ea-9fad-9ef743b451c9.png)

**Comment by ivopaunov** [comment] 2020-02-01 22:26
fixed with https://github.com/AdExNetwork/adex-platform/commit/b9de393bdea9322f6b479a79f970bbf5bee54db8

There was real problem, because the initial validation was not correct. Also this error was possible when go back to this step from next one.

**Closed** 2020-02-01 22:43 UTC
Labels: bug
