### ISSUE TITLE
bug: CPM calculation sometimes inconsistent

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-platform#280] opened 2020-01-02 19:48 UTC
**Describe the bug**
I saw a CPM figure of over 100 SAI. It was as an advertiser. After a little while, it updated to the real figure: 0.19 SAI

I suspect CPM is calculated from two different stats aquired asynchronously, and we had one of them cached and the other one refreshed - hence why the discrepancy.

**Expected behavior**
If you don't have enough recent data to calculate CPM, show it as loading

**Screenshots**
I could not get one

**Comment by rori4** [comment] 2020-01-20 10:46
I can't reproduce it now. I believe that this was fixed with reducing the requests for the analytics and now they update fast enough. 
Any way of reproducing this?

**Comment by Ivshti** [comment] 2020-01-20 11:26
It’s hard to reproduce now that the backend is fast

Just show the loading indicator if the data is old... that is sufficient to solve it

**Closed** 2020-01-31 14:12 UTC
Labels: bug
